/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-26 15:43:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1679827971000L));
    _jspx_dependants.put("jar:file:/Users/ijin/Documents/workspace/5_server/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/community/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>community</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/main-style.css\">\n");
      out.write("\n");
      out.write("    <!--  fontawesome 사이트 아이콘 이용   -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/f7459b8054.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  \n");
      out.write("    <main>\n");
      out.write("    \n");
      out.write("    	<!-- \n");
      out.write("    		jsp:include 태그\n");
      out.write("    		 다른 jsp 파일의 내용을 해당 위치에 포함시킴\n");
      out.write("    		 * 외부 요청 주소 X (인터넷주소, 최상위 : /community),\n");
      out.write("    		   내부 접근 경로 O (파일경로, 최상위 : /webapp)\n");
      out.write("    	 -->\n");
      out.write("    \n");
      out.write("        <!-- header include -->\n");
      out.write("        \n");
      out.write("        <!-- 내부 접근 절대 경로 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("        <section class=\"content\">\n");
      out.write("            <section class=\"content-1\">\n");
      out.write("            	\n");
      out.write("            	<h3>회원 정보 조회(AJAX)</h3>\n");
      out.write("            \n");
      out.write("            	<p>이메일을 입력받아 일치하는 회원 정보를 출력</p>\n");
      out.write("            	\n");
      out.write("            	이메일 : <input type=\"text\" id=\"in1\"/>\n");
      out.write("            	<button id=\"select1\">조회</button>\n");
      out.write("            	<div id=\"result1\" style=\"height: 150px;\"></div>\n");
      out.write("\n");
      out.write("                <hr>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <h3>회원 목록 조회</h3>\n");
      out.write("            \n");
      out.write("            	<p>일정 시간 마다 비동기로 회원 목록(회원 번호, 이메일, 닉네임) 조회</p>\n");
      out.write("            	\n");
      out.write("            	<table id=\"memberTable\" border=\"1\">\n");
      out.write("            	<tr>\n");
      out.write("            	<td>회원번호</td>\n");
      out.write("            	<td>이메일</td>\n");
      out.write("            	<td>닉네임</td>\n");
      out.write("            	\n");
      out.write("            	</tr>\n");
      out.write("            	\n");
      out.write("            	\n");
      out.write("           \n");
      out.write("            	</table>\n");
      out.write("\n");
      out.write("                <hr>\n");
      out.write("                \n");
      out.write("            \n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"content-2\">\n");
      out.write("\n");
      out.write("                <form action=\"#\" name=\"login-frm\">\n");
      out.write("        \n");
      out.write("                    <!-- 아이디, 비밀번호, 로그인 버튼 -->\n");
      out.write("                    <fieldset id=\"id-pw-area\">\n");
      out.write("                        <section>\n");
      out.write("                            <input type=\"text\" name=\"inputId\"\n");
      out.write("                             placeholder=\"아이디\" autocomplete=\"off\">\n");
      out.write("                            <!-- autocomplete=\"off\" : 자동완성 사용 X -->\n");
      out.write("        \n");
      out.write("                            <input type=\"password\" name=\"inputPw\" placeholder=\"비밀번호\">\n");
      out.write("                        </section>\n");
      out.write("        \n");
      out.write("                        <section>\n");
      out.write("                            <!-- type=\"submit\"이 기본값 -->\n");
      out.write("                            <button>로그인</button>\n");
      out.write("                        </section>\n");
      out.write("                    </fieldset>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("                    <!-- label 태그 내부에 input태그를 작성하면 자동 연결됨 -->\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\" name=\"saveId\"> 아이디 저장\n");
      out.write("                    </label>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("                    <!-- 회원가입 / ID/PW 찾기 -->\n");
      out.write("                    <article id=\"signUp-find-area\">\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                   \n");
      out.write("                    \n");
      out.write("                    <!-- <a href=\"\"WEB_INF/views/member/signUp.jsp  -->\n");
      out.write("                    <!-- WEB_INF폴더는 외부로부터 직접적으로 요청할수 없는폴더\n");
      out.write("                    왜? 중요한 코드(자바,sql 설정관련) 가 위치하는 폴더로써\n");
      out.write("                    외부로부터 접근을 차잔하기 위해서.\n");
      out.write("                   -> servlet을 이용해서 내부 접근(forward)은 가능 -->\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signUp\">회원가입</a>\n");
      out.write("                        <span>|</span>\n");
      out.write("                        <a href=\"#\">ID/PW찾기</a>\n");
      out.write("                    </article>\n");
      out.write("                </form>\n");
      out.write("            </section>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("    \n");
      out.write("    <!-- footer include -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write(" 	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	<!--  main.js 연결 -->\n");
      out.write("	<script src=\"resources/js/main_2.js\"></script>\n");
      out.write("	<script src=\"resources/js/main_3.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
